# ======================================================
# Stage 1: Builder
# ======================================================
FROM python:3.12-slim AS builder

# Prevents python write .pyc files and log immediately

ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1

WORKDIR /app

# Install curl and build-essential for install uv

RUN apt-get update && pat-get install -y --no-install-recommends curl build-essential && \
  curl -LsSf https://astral.sh/uv/install.sh | sh && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.local/bin:${PATH}"

# Copy configfile for Docker Cache

COPY pyproject.toml ./


