replicaCount: 1

image:
  repository: ghcr.io/openclaw/openclaw
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 18789

ingress:
  enabled: true
  className: "traefik"
  host: openclaw.coregate.dev
  annotations: {}

persistence:
  enabled: true
  storageClass: "local-path"
  configSize: 2Gi
  workspaceSize: 5Gi
