apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-telegram-es
  namespace: openclaw
spec:
  refreshInterval: "15s" # ให้ Sync ทุกๆ 15 วินาที
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: telegram-secret # ชื่อ Secret ที่จะไปโผล่ใน Kubernetes
    creationPolicy: Owner
  data:
  - secretKey: TELEGRAM_TOKEN # Key ใน k8s Secret
    remoteRef:
      key: openclaw/telegram # Path ใน Vault
      property: token        # Key ใน Vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-gemini-es
  namespace: openclaw
spec:
  refreshInterval: "15s" # ให้ Sync ทุกๆ 15 วินาที
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gemini-secret # ชื่อ Secret ที่จะไปโผล่ใน Kubernetes
    creationPolicy: Owner
  data:
  - secretKey: GEMINI_API_KEY # Key ใน k8s Secret
    remoteRef:
      key: openclaw/gemini # Path ใน Vault
      property: api_key        # Key ใน Vault